name: Build and Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libboost-all-dev \
          libeigen3-dev

    - name: Create build directory
      run: mkdir -p build

    - name: Configure with CMake
      run: cmake ..
      working-directory: ./build

    - name: Build the project
      run: make -j$(nproc)
      working-directory: ./build

    - name: Run idresnet.bin
      run: ./idresnet.bin
      working-directory: ./build

    - name: Run exp.bin
      run: ./exp_cc.bin
      working-directory: ./build
